---
- name: Apply common configuration to all hosts
  hosts: all
  roles:
    - common

- name: Configure Consul servers
  hosts: servers
  roles:
    - servers/consul
    - servers/nomad
    - nomad_cloudflare_tunnel
    - traefik

- name: Configure Consul and Nomad clients
  hosts: clients
  roles:
    - clients/consul
    - clients/nomad
    - clients/docker
    - traefik
    - nomad_test_app