- name: Ensure Nomad configuration directory exists
  file:
    path: /etc/nomad.d
    state: directory
    mode: '0755'

- name: Ensure alloc_mounts directory exists
  file:
    path: /var/lib/alloc_mounts
    state: directory
    mode: '0755'
    owner: nomad
    group: nomad

- name: Deploy Nomad client configuration
  template:
    src: client.hcl.j2
    dest: /etc/nomad.d/client.hcl
    mode: '0644'
  notify: Restart Nomad

- name: Enable and start Nomad service
  systemd:
    name: nomad
    enabled: yes
    state: started
  become: yes

- name: Wait for Nomad service to become active
  command: systemctl is-active nomad
  register: nomad_service_status
  retries: 24
  delay: 5
  until: nomad_service_status.stdout.strip() == "active"
  changed_when: false

- name: Check Nomad client status
  shell: "nomad node-status"
  register: nomad_status
  changed_when: false
  failed_when: false

- name: Wait for Nomad clients to register
  shell: |
    nomad node-status | grep -q 'ready'
  register: nomad_clients_ready
  retries: 24
  delay: 5
  until: nomad_clients_ready.rc == 0
  changed_when: false
