---
- name: Ensure Traefik config directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: nomad
    group: nomad
    mode: '0755'
  with_items:
    - "/mnt/data/traefik-config"
    - "/mnt/data/traefik-config/dynamic"
  tags: [traefik, traefik_config]

- name: Render Traefik static config
  template:
    src: traefik.yml.j2
    dest: "/mnt/data/traefik-config/traefik.yml"
    owner: nomad
    group: nomad
    mode: '0644'
  tags: [traefik, traefik_config]

- name: Render Traefik ACME file
  template:
    src: acme.json.j2
    dest: "/mnt/data/traefik-config/acme.json"
    owner: nomad
    group: nomad
    mode: '0600'
  tags: [traefik, traefik_config]

- name: Render Traefik Nomad job spec
  template:
    src: traefik.nomad.j2
    dest: "{{ traefik_nomad_job_path }}"
    owner: "{{ ansible_user }}"
    mode: '0644'
  tags: [traefik, traefik_job]

- name: Run or update Traefik Nomad job (submit from first server only)
  command: >
    nomad job run {{ traefik_nomad_job_path }}
  when: inventory_hostname == groups['servers'][0]
  tags: [traefik, traefik_deploy, deploy_traefik]
